## [[Iterations]]
	- Nish Example:
	  ```javascript
	  let nums = [ 10, 6, 22, -7, 3];
	   // For each
	  function highestForOfLoop(nums) {
	   	let highest = nums[0]
	      // Iterate over each number in the array
	      for (let num of nums){
	        	// If the current number is greater than the Highest
	      	if(num > highest){
	            highest = num;
	          }
	      }
	    	return highest;
	  }
	   
	  function highestForLoop(nums){
	  	let highest = 0;
	      for(let i = 0; i < nums.length; i++){
	          if(nums[i] > highest){
	              highest = nums[i];
	          }
	      }
	      return highest;
	  }
	   
	  function highestWhileLoop(nums){
	   	let highest = 0;
	      let counter = 0;
	      while(counter < nums.length){
	          if(nums[counter] > highest){
	              highest = nums[counter];
	          }
	          ++counter;
	      }
	      return highest;
	  }
	   // Always executed at least once
	  function highestDoWhileLoop(nums){
	   	let highest = 0;
	      let counter = 0;
	      do {
	          if(nums[counter] > highest){
	              highest = nums[counter];
	          }
	          ++counter;
	      } while(counter < nums.length) 
	      return highest;
	  }
	  ```
- ## [[Error Handling]]
	- Nish Example of Exceptions:
	  ```javascript
	  function sumOfArray(arr) {
	      let sum = 0;
	    	try {
	        for (let i = 0; i < arr.length; i++) {
	            sum += arr[i];
	        }
	        return sum;
	      } catch(err){
	        console.log(err);
	      } finally {
	        console.log("Finally Log executed");
	      }
	  }
	  ```
	- Nish Throw Example:
	  ```javascript
	  function divide(a,b){
	    if(b === 0){
	      throw new Error("cannot divide by 0!");
	    }
	    return a/b;
	  }
	  ```
	- If calling a method which throws an exception, best practice is to wrap your code in a try-catch block.